# Chapter 9: Approximating Eigenvalues

## 9.4 Householder's Method

In [1]:
import numpy as np
from copy import deepcopy

In [3]:
def householder(A, printAll=False):  
    n = len(A)    
    A_list = [A.astype(float)]
    isSymmetric = True
    
    if not np.allclose(A.transpose(), A):
        print("Note: Matrix is not symmetric.")
        isSymmetric = False
    
    for k in range(n-2):
        
        #Initialize variables
        v = np.zeros((n,1))
        u = np.zeros((n,1))
        z = np.zeros((n,1))
        
        if not isSymmetric:
            y = np.zeros((n,1))
        
        A_current = deepcopy(A_list[k])
        A_next = deepcopy(A_list[k])

        q = np.dot(A_current[k+1:,k],A_current[k+1:,k])

        if A_current[k+1,k] == 0:
            alpha = -np.sqrt(q)
        else:
            alpha = -(np.sqrt(q)*A_current[k+1,k])/(np.abs(A_current[k+1,k]))

        RSQ = alpha**2 - alpha*A_current[k+1,k]

        v[k+1] = A_current[k+1,k] - alpha
        v[k+2:] = A_current[k+2:,k:k+1]

        if isSymmetric:
            u = (1/RSQ)*np.dot(A_current,v)
        else:
            u = (1/RSQ)*np.dot(A_current[:,k+1:],v[k+1:])
            y = (1/RSQ)*np.dot(A_current[k+1:,:].T,v[k+1:])
        
        PROD = np.dot(v.T,u)

        if isSymmetric:
            z = u - (1/(2*RSQ))*np.dot(v.T,u)*v
        else:
            z = u - (PROD/RSQ)*v
            
        if isSymmetric:
            A_next = A_current - np.dot(v,z.T) - np.dot(z,v.T)
            A_next[-1,-1] = A_current[-1,-1] - 2*v[-1]*z[-1]
            
            A_next[k,k+2:] = np.zeros(n-k-2)
            A_next[k+2:,k] = np.zeros(n-k-2)

            A_next[k+1,k] = A_current[k+1,k] - v[k+1]*z[k]
            A_next[k,k+1] = A_next[k+1,k]
            
        else:
            A_next[:k+1,k+1:] = A_current[:k+1,k+1:] - np.dot(z[:k+1],v[k+1:].T)
            A_next[k+1:,:k+1] = A_current[k+1:,:k+1] - np.dot(v[k+1:],y[:k+1].T)
            
            A_next[k+1:,k+1:] = A_current[k+1:,k+1:] - np.dot(z[k+1:],v[k+1:].T) - np.dot(v[k+1:],y[k+1:].T)
            
        A_list.append(A_next)
    
    if printAll:
        return np.around(A_list, decimals=6) 
    else:
        return np.around(A_list[-1], decimals=6) 

### Symmetric Matrix

In [4]:
A = np.array([
        [4,1,-2,2],
        [1,2,0,1],
        [-2,0,3,-2],
        [2,1,-2,-1]
    ])

householder(A, printAll=True)

array([[[ 4.      ,  1.      , -2.      ,  2.      ],
        [ 1.      ,  2.      ,  0.      ,  1.      ],
        [-2.      ,  0.      ,  3.      , -2.      ],
        [ 2.      ,  1.      , -2.      , -1.      ]],

       [[ 4.      , -3.      ,  0.      ,  0.      ],
        [-3.      ,  3.333333,  1.      ,  1.333333],
        [ 0.      ,  1.      ,  1.666667, -1.333333],
        [ 0.      ,  1.333333, -1.333333, -1.      ]],

       [[ 4.      , -3.      ,  0.      ,  0.      ],
        [-3.      ,  3.333333, -1.666667,  0.      ],
        [ 0.      , -1.666667, -1.32    ,  0.906667],
        [ 0.      ,  0.      ,  0.906667,  1.986667]]])

In [100]:
E1a = np.array([
        [12,10,4],
        [10,8,-5],
        [4,-5,3]
    ])

householder(E1a)

array([[ 12.      , -10.77033 ,   0.      ],
       [-10.77033 ,   3.862069,   5.344828],
       [  0.      ,   5.344828,   7.137931]])

In [101]:
E1b = np.array([
        [2,-1,-1],
        [-1,2,-1],
        [-1,-1,2]
    ])

householder(E1b)

array([[ 2.      ,  1.414214,  0.      ],
       [ 1.414214,  1.      , -0.      ],
       [ 0.      , -0.      ,  3.      ]])

In [102]:
E1c = np.array([
        [1,1,1],
        [1,1,0],
        [1,0,1]
    ])

householder(E1c)

array([[ 1.      , -1.414214,  0.      ],
       [-1.414214,  1.      , -0.      ],
       [ 0.      , -0.      ,  1.      ]])

In [103]:
E1d = np.array([
        [4.75, 2.25, -0.25000001],
        [2.25, 4.75, 1.25],
        [-0.25, 1.25, 4.75]
    ])

householder(E1d)

array([[ 4.75    , -2.263846,  0.      ],
       [-2.263846,  4.47561 , -1.219512],
       [ 0.      , -1.219512,  5.02439 ]])

### Non-symmetric Matrix

In [107]:
E3a = np.array([
        [2,-1,3],
        [2,0,1],
        [-2,1,4]
    ])

householder(E3a)

Note: Matrix is not symmetric.


array([[ 2.      ,  2.828427,  1.414214],
       [-2.828427,  1.      ,  2.      ],
       [-0.      ,  2.      ,  3.      ]])

In [106]:
E3b = np.array([
        [-1,2,3],
        [2,3,-2,],
        [3,1,-1]
    ])

householder(E3b)

Note: Matrix is not symmetric.


array([[-1.      , -3.605551, -0.      ],
       [-3.605551, -0.230769,  3.153846],
       [-0.      ,  0.153846,  2.230769]])

In [104]:
E3c = np.array([
        [5,-2,-3,4],
        [0,4,2,-1],
        [1,3,-5,2],
        [-1,4,0,3]
    ])

householder(E3c)

Note: Matrix is not symmetric.


array([[ 5.      ,  4.949747, -1.432078, -1.564977],
       [-1.414214, -2.      , -2.485551,  1.822645],
       [-0.      , -5.43139 , -1.423729, -2.648654],
       [-0.      ,  0.      ,  1.593986,  5.423729]])

In [105]:
E3d = np.array([
        [4.,-1,-1,-1],
        [-1,4,0,-1],
        [-1,-1,4,-1],
        [-1,-1,-1,4]
    ])

householder(E3d)

Note: Matrix is not symmetric.


array([[ 4.      ,  1.732051,  0.      ,  0.      ],
       [ 1.732051,  2.333333,  0.235702,  0.408248],
       [ 0.      , -0.471405,  4.666667, -0.57735 ],
       [ 0.      ,  0.      , -0.      ,  5.      ]])