In [86]:
import numpy as np

In [229]:
def householder(A, printAll=False):  
    n = len(A)    
    A_list = [A]
    isSymmetric = True
    
    if not np.allclose(A.transpose(), A):
        print("Note: Matrix is not symmetric.")
        isSymmetric = False
    
    for k in range(n-2):
        
        v = np.zeros((n,1))
        u = np.zeros((n,1))
        z = np.zeros((n,1))
        
        if not isSymmetric:
            y = np.zeros((n,1))
        
        A_current = A_list[k]
        A_next = A_list[k]       

        q = np.dot(A_current[k+1:,k],A_current[k+1:,k])

        if A_current[k+1,k] == 0:
            alpha = -np.sqrt(q)
        else:
            alpha = -(np.sqrt(q)*A_current[k+1,k])/(np.abs(A_current[k+1,k]))

        RSQ = alpha**2 - alpha*A_current[k+1,k]

        v[k+1] = A_current[k+1,k] - alpha
        v[k+2:] = A_current[k+2:,k:k+1]

        if isSymmetric:
            u = (1/RSQ)*np.dot(A_current,v)
        else:
            u = (1/RSQ)*np.dot(A_current[:,k+1:],v[k+1:])
            y = (1/RSQ)*np.dot(A_current[k+1:,:].T,v[k+1:])
            
        PROD = np.dot(v.T,u)

        if isSymmetric:
            z = u - (1/(2*RSQ))*np.dot(v.T,u)*v
        else:
            z = u - (PROD/RSQ)*v

        if isSymmetric:
            A_next = A_current - np.dot(v,z.T) - np.dot(z,v.T)
            A_next[-1,-1] = A_current[-1,-1] - 2*v[-1]*z[-1]
            
            A_next[k,k+2:] = np.zeros(n-k-2)
            A_next[k+2:,k] = np.zeros(n-k-2)

            A_next[k+1,k] = A_current[k+1,k] - v[k+1]*z[k]
            A_next[k,k+1] = A_next[k+1,k]
            
        else:
            A_next[:k+1,k+1:] = A_current[:k+1,k+1:] - np.dot(z[:k+1],v[k+1:].T)
            A_next[k+1:,:k+1] = A_current[k+1:,:k+1] - np.dot(v[k+1:],y[:k+1].T)
            
            A_next[k+1:,k+1:] = A_current[k+1:,k+1:] - np.dot(z[k+1:],v[k+1:].T) - np.dot(y[k+1:],v[k+1:].T)
        
        A_list.append(A_next)
    
    if printAll:
        return np.around(A_list, decimals=7) 
    else:
        return np.around(A_list[-1], decimals=7) 

### Symmetric Matrix

In [230]:
A = np.array([
        [4,1,-2,2],
        [1,2,0,1],
        [-2,0,3,-2],
        [2,1,-2,-1]
    ])

householder(A)

array([[ 4.       , -3.       ,  0.       ,  0.       ],
       [-3.       ,  3.3333333, -1.6666667,  0.       ],
       [ 0.       , -1.6666667, -1.32     ,  0.9066667],
       [ 0.       ,  0.       ,  0.9066667,  1.9866667]])

In [231]:
E9_4_1a = np.array([
        [12,10,4],
        [10,8,-5],
        [4,-5,3]
    ])

householder(E9_4_1a)

array([[ 12.       , -10.7703296,   0.       ],
       [-10.7703296,   3.862069 ,   5.3448276],
       [  0.       ,   5.3448276,   7.137931 ]])

In [232]:
E9_4_1b = np.array([
        [2,-1,-1],
        [-1,2,-1],
        [-1,-1,2]
    ])

householder(E9_4_1b)

array([[ 2.       ,  1.4142136,  0.       ],
       [ 1.4142136,  1.       , -0.       ],
       [ 0.       , -0.       ,  3.       ]])

In [233]:
E9_4_1c = np.array([
        [1,1,1],
        [1,1,0],
        [1,0,1]
    ])

householder(E9_4_1c)

array([[ 1.       , -1.4142136,  0.       ],
       [-1.4142136,  1.       , -0.       ],
       [ 0.       , -0.       ,  1.       ]])

In [234]:
E9_4_1d = np.array([
        [4.75, 2.25, -0.25000001],
        [2.25, 4.75, 1.25],
        [-0.25, 1.25, 4.75]
    ])

householder(E9_4_1d)

array([[ 4.75     , -2.2638463,  0.       ],
       [-2.2638463,  4.4756098, -1.2195122],
       [ 0.       , -1.2195122,  5.0243902]])

### Non-symmetric Matrix

In [235]:
B = np.array([
        [4.,-1,-1,-1],
        [-1,4,0,-1],
        [-1,-1,4,-1],
        [-1,-1,-1,4]
    ])

In [237]:
householder(B, printAll=True)

Note: Matrix is not symmetric.


array([[[ 4.       , -1.7320508,  0.       ,  0.       ],
        [-1.7320508,  2.3333333, -1.6864404, -0.3468528],
        [ 0.       ,  1.3671985,  4.8057461, -0.1171805],
        [ 0.       ,  0.       ,  0.7815601,  4.8609205]],

       [[ 4.       , -1.7320508,  0.       ,  0.       ],
        [-1.7320508,  2.3333333, -1.6864404, -0.3468528],
        [ 0.       ,  1.3671985,  4.8057461, -0.1171805],
        [ 0.       ,  0.       ,  0.7815601,  4.8609205]],

       [[ 4.       , -1.7320508,  0.       ,  0.       ],
        [-1.7320508,  2.3333333, -1.6864404, -0.3468528],
        [ 0.       ,  1.3671985,  4.8057461, -0.1171805],
        [ 0.       ,  0.       ,  0.7815601,  4.8609205]]])